"""Minimal async client for an ADB *server* (the smart-socket protocol on :5037).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home

The projector's adbd (Android 14) only accepts TLS connections from a paired key,
which pure-Python ADB libraries don't do. So a regular `adb` server runs next to
Home Assistant (container "adb-server", holding the paired key) and this client
just asks it to connect/run shell commands.
"""

from __future__ import annotations

import asyncio

TIMEOUT = 8


class AdbError(Exception):
    """ADB server or device error."""


class AdbClient:
    """Talks to `adb -a -P 5037 server`."""

    def __init__(self, server: str, port: int, device: str) -> None:
        self._server = server
        self._port = port
        self.serial = device

    async def _open(self) -> tuple[asyncio.StreamReader, asyncio.StreamWriter]:
        try:
            return await asyncio.wait_for(
                asyncio.open_connection(self._server, self._port), TIMEOUT
            )
        except (OSError, asyncio.TimeoutError) as err:
            raise AdbError(f"ADB server {self._server}:{self._port} unreachable: {err}") from err

    @staticmethod
    async def _request(reader, writer, cmd: str) -> None:
        writer.write(f"{len(cmd):04x}{cmd}".encode())
        await writer.drain()
        status = await asyncio.wait_for(reader.readexactly(4), TIMEOUT)
        if status != b"OKAY":
            msg = b""
            try:
                size = int((await asyncio.wait_for(reader.readexactly(4), TIMEOUT)), 16)
                msg = await asyncio.wait_for(reader.readexactly(size), TIMEOUT)
            except Exception:  # noqa: BLE001
                pass
            raise AdbError(f"{cmd}: {status!r} {msg.decode(errors='ignore')}")

    async def _host(self, cmd: str) -> str:
        reader, writer = await self._open()
        try:
            await self._request(reader, writer, cmd)
            size = int((await asyncio.wait_for(reader.readexactly(4), TIMEOUT)), 16)
            return (await asyncio.wait_for(reader.readexactly(size), TIMEOUT)).decode(errors="ignore")
        except (asyncio.IncompleteReadError, asyncio.TimeoutError, ValueError) as err:
            raise AdbError(f"{cmd}: {err}") from err
        finally:
            writer.close()

    async def async_ensure_connected(self) -> None:
        devices = await self._host("host:devices")
        for line in devices.splitlines():
            serial, _, state = line.partition("\t")
            if serial == self.serial and state == "device":
                return
        answer = await self._host(f"host:connect:{self.serial}")
        if "connected" not in answer:
            raise AdbError(answer.strip() or "connect failed")

    async def async_shell(self, command: str) -> str:
        await self.async_ensure_connected()
        reader, writer = await self._open()
        try:
            await self._request(reader, writer, f"host:transport:{self.serial}")
            await self._request(reader, writer, f"shell:{command}")
            return (await asyncio.wait_for(reader.read(-1), TIMEOUT)).decode(errors="ignore")
        except (asyncio.IncompleteReadError, asyncio.TimeoutError) as err:
            raise AdbError(f"shell {command!r}: {err}") from err
        finally:
            writer.close()

    async def async_launch(self, package: str) -> None:
        out = await self.async_shell(
            f"monkey -p {package} -c android.intent.category.LEANBACK_LAUNCHER 1"
        )
        if "No activities found" in out or "monkey aborted" in out:
            out = await self.async_shell(f"monkey -p {package} -c android.intent.category.LAUNCHER 1")
            if "No activities found" in out or "monkey aborted" in out:
                raise AdbError(f"cannot launch {package}")

    async def async_current_package(self) -> str | None:
        out = await self.async_shell("dumpsys activity activities | grep -m1 topResumedActivity")
        # topResumedActivity=ActivityRecord{8047fbc u0 com.stremio.one/com.stremio.tv.MainActivity t413}
        for token in out.split():
            if "/" in token and "." in token.split("/")[0]:
                return token.split("/")[0]
        return None
