"""Async client for the projector's local "Lumina Go" HTTP API (port 8899).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home

Endpoints (no authentication on the LAN):
  GET  /api/v1/device   -> {"name", "model", "model_label", "version", "ip",
                            "capabilities": [...], "commands": [...], ...}
  POST /api/v1/command  {"command": "VOL_UP", "long_press": false}
                        -> 200 {"status": "ok", ...} / 400 {"error": "Unknown command..."}
"""

from __future__ import annotations

import asyncio
from typing import Any

import aiohttp

from .const import BLOCKED_COMMANDS

TIMEOUT = aiohttp.ClientTimeout(total=5)


class ProjectorError(Exception):
    """Generic API error."""


class ProjectorOffline(ProjectorError):
    """The projector did not answer (off, or Wi-Fi down)."""


class ProjectorApi:
    """Tiny client for the Lumina Go API."""

    def __init__(self, session: aiohttp.ClientSession, host: str, port: int) -> None:
        self._session = session
        self._base = f"http://{host}:{port}/api/v1"

    async def async_get_device(self) -> dict[str, Any]:
        """Return the device info; raises ProjectorOffline if unreachable."""
        try:
            async with self._session.get(f"{self._base}/device", timeout=TIMEOUT) as resp:
                if resp.status != 200:
                    raise ProjectorError(f"HTTP {resp.status} on /device")
                data = await resp.json(content_type=None)
        except (aiohttp.ClientConnectionError, asyncio.TimeoutError) as err:
            raise ProjectorOffline(str(err)) from err
        except aiohttp.ClientError as err:
            raise ProjectorError(str(err)) from err
        if not isinstance(data, dict):
            raise ProjectorError("Unexpected /device payload")
        return data

    async def async_send_command(self, command: str, long_press: bool = False) -> None:
        """Send one key/command. Blocked (destructive) commands are refused."""
        if command in BLOCKED_COMMANDS:
            raise ProjectorError(f"Command {command} is blocked in Home Assistant")
        body = {"command": command}
        if long_press:
            body["long_press"] = True
        try:
            async with self._session.post(
                f"{self._base}/command", json=body, timeout=TIMEOUT
            ) as resp:
                if resp.status != 200:
                    text = (await resp.text())[:200]
                    raise ProjectorError(f"HTTP {resp.status}: {text}")
        except (aiohttp.ClientConnectionError, asyncio.TimeoutError) as err:
            raise ProjectorOffline(str(err)) from err
        except aiohttp.ClientError as err:
            raise ProjectorError(str(err)) from err
