"""Binary sensors for HY300 Projetor.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from homeassistant.components.binary_sensor import (
    BinarySensorDeviceClass,
    BinarySensorEntity,
)
from homeassistant.const import EntityCategory
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback

from . import ProjectorConfigEntry
from .entity import ProjectorEntity


async def async_setup_entry(
    hass: HomeAssistant,
    entry: ProjectorConfigEntry,
    async_add_entities: AddConfigEntryEntitiesCallback,
) -> None:
    if entry.runtime_data.adb:
        async_add_entities([ProjectorAdbSensor(entry.runtime_data)])


class ProjectorAdbSensor(ProjectorEntity, BinarySensorEntity):
    """On when the last poll could talk to the projector over ADB (apps can be opened)."""

    _attr_name = "ADB"
    _attr_device_class = BinarySensorDeviceClass.CONNECTIVITY
    _attr_entity_category = EntityCategory.DIAGNOSTIC

    def __init__(self, coordinator) -> None:
        super().__init__(coordinator, "adb")

    @property
    def is_on(self) -> bool:
        return self.coordinator.data.online and self.coordinator.data.adb_ok
