"""Buttons for common projector keys.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from dataclasses import dataclass

from homeassistant.components.button import ButtonEntity, ButtonEntityDescription
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback

from . import ProjectorConfigEntry
from .api import ProjectorError
from .entity import ProjectorEntity


@dataclass(frozen=True, kw_only=True)
class ProjectorButtonDescription(ButtonEntityDescription):
    """A button that sends one API command."""

    command: str


BUTTONS: tuple[ProjectorButtonDescription, ...] = (
    ProjectorButtonDescription(key="up", name="Cima", icon="mdi:chevron-up", command="NAV_UP"),
    ProjectorButtonDescription(key="down", name="Baixo", icon="mdi:chevron-down", command="NAV_DOWN"),
    ProjectorButtonDescription(key="left", name="Esquerda", icon="mdi:chevron-left", command="NAV_LEFT"),
    ProjectorButtonDescription(key="right", name="Direita", icon="mdi:chevron-right", command="NAV_RIGHT"),
    ProjectorButtonDescription(key="ok", name="OK", icon="mdi:checkbox-blank-circle-outline", command="NAV_OK"),
    ProjectorButtonDescription(key="back", name="Voltar", icon="mdi:arrow-left", command="NAV_BACK"),
    ProjectorButtonDescription(key="home", name="Início", icon="mdi:home", command="NAV_HOME"),
    ProjectorButtonDescription(key="menu", name="Menu", icon="mdi:menu", command="NAV_MENU"),
    ProjectorButtonDescription(key="settings", name="Configurações", icon="mdi:cog", command="SETTINGS"),
    ProjectorButtonDescription(key="input", name="Entrada", icon="mdi:video-input-hdmi", command="INPUT_SOURCE"),
    ProjectorButtonDescription(key="focus_up", name="Foco +", icon="mdi:image-filter-center-focus-strong", command="FOCUS_UP"),
    ProjectorButtonDescription(key="focus_down", name="Foco −", icon="mdi:image-filter-center-focus-weak", command="FOCUS_DOWN"),
    ProjectorButtonDescription(key="auto_focus", name="Foco automático", icon="mdi:image-filter-center-focus", command="AUTO_FOCUS"),
    ProjectorButtonDescription(key="keystone", name="Keystone", icon="mdi:trapezoid", command="KEYSTONE"),
    ProjectorButtonDescription(key="zoom_in", name="Zoom +", icon="mdi:magnify-plus", command="ZOOM_IN"),
    ProjectorButtonDescription(key="zoom_out", name="Zoom −", icon="mdi:magnify-minus", command="ZOOM_OUT"),
    ProjectorButtonDescription(key="play_pause", name="Play/Pause", icon="mdi:play-pause", command="MEDIA_PLAY_PAUSE"),
    ProjectorButtonDescription(key="sleep", name="Dormir", icon="mdi:sleep", command="SLEEP"),
)


async def async_setup_entry(
    hass: HomeAssistant,
    entry: ProjectorConfigEntry,
    async_add_entities: AddConfigEntryEntitiesCallback,
) -> None:
    coordinator = entry.runtime_data
    async_add_entities(ProjectorButton(coordinator, d) for d in BUTTONS)


class ProjectorButton(ProjectorEntity, ButtonEntity):
    """Available only while the projector is on."""

    entity_description: ProjectorButtonDescription

    def __init__(self, coordinator, description: ProjectorButtonDescription) -> None:
        super().__init__(coordinator, f"button_{description.key}")
        self.entity_description = description

    @property
    def available(self) -> bool:
        return super().available and self.coordinator.data.online

    async def async_press(self) -> None:
        try:
            await self.coordinator.api.async_send_command(self.entity_description.command)
        except ProjectorError as err:
            raise HomeAssistantError(str(err)) from err
