"""Config and options flow for HY300 Projetor.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from typing import Any

import voluptuous as vol

from homeassistant.config_entries import ConfigEntry, ConfigFlow, ConfigFlowResult, OptionsFlow
from homeassistant.const import CONF_HOST, CONF_NAME, CONF_PORT
from homeassistant.core import callback
from homeassistant.helpers import selector
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from .api import ProjectorApi, ProjectorError, ProjectorOffline
from .const import (
    CONF_ADB_ENABLED,
    CONF_ADB_PORT,
    CONF_ADB_SERVER,
    DEFAULT_ADB_PORT,
    DEFAULT_ADB_SERVER,
    CONF_IR_COMMAND,
    CONF_IR_DEVICE,
    CONF_IR_REMOTE,
    CONF_IR_RETRY,
    DEFAULT_IR_COMMAND,
    DEFAULT_IR_RETRY,
    DEFAULT_IR_DEVICE,
    DEFAULT_NAME,
    DEFAULT_PORT,
    DOMAIN,
)


class Hy300ConfigFlow(ConfigFlow, domain=DOMAIN):
    """Ask for the projector address and check the API answers."""

    VERSION = 1

    async def async_step_user(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult:
        errors: dict[str, str] = {}
        if user_input is not None:
            host = user_input[CONF_HOST].strip()
            port = user_input.get(CONF_PORT, DEFAULT_PORT)
            api = ProjectorApi(async_get_clientsession(self.hass), host, port)
            try:
                device = await api.async_get_device()
            except ProjectorOffline:
                errors["base"] = "cannot_connect"
            except ProjectorError:
                errors["base"] = "unknown"
            else:
                await self.async_set_unique_id(f"{device.get('name', 'hy300')}_{host}")
                self._abort_if_unique_id_configured()
                return self.async_create_entry(
                    title=user_input.get(CONF_NAME) or DEFAULT_NAME,
                    data={CONF_HOST: host, CONF_PORT: port},
                )

        schema = vol.Schema(
            {
                vol.Required(CONF_HOST): str,
                vol.Optional(CONF_PORT, default=DEFAULT_PORT): vol.All(int, vol.Range(min=1, max=65535)),
                vol.Optional(CONF_NAME, default=DEFAULT_NAME): str,
            }
        )
        return self.async_show_form(step_id="user", data_schema=schema, errors=errors)

    @staticmethod
    @callback
    def async_get_options_flow(config_entry: ConfigEntry) -> OptionsFlow:
        return Hy300OptionsFlow()


class Hy300OptionsFlow(OptionsFlow):
    """IR blaster used to turn the projector on (its API is down while off)."""

    async def async_step_init(self, user_input: dict[str, Any] | None = None) -> ConfigFlowResult:
        if user_input is not None:
            return self.async_create_entry(data=user_input)

        opts = self.config_entry.options
        schema = vol.Schema(
            {
                vol.Optional(
                    CONF_IR_REMOTE,
                    description={"suggested_value": opts.get(CONF_IR_REMOTE)},
                ): selector.EntitySelector(selector.EntitySelectorConfig(domain="remote")),
                vol.Optional(
                    CONF_IR_DEVICE, default=opts.get(CONF_IR_DEVICE, DEFAULT_IR_DEVICE)
                ): str,
                vol.Optional(
                    CONF_IR_COMMAND, default=opts.get(CONF_IR_COMMAND, DEFAULT_IR_COMMAND)
                ): str,
                vol.Optional(
                    CONF_IR_RETRY, default=opts.get(CONF_IR_RETRY, DEFAULT_IR_RETRY)
                ): bool,
                vol.Optional(
                    CONF_ADB_ENABLED, default=opts.get(CONF_ADB_ENABLED, False)
                ): bool,
                vol.Optional(
                    CONF_ADB_SERVER, default=opts.get(CONF_ADB_SERVER, DEFAULT_ADB_SERVER)
                ): str,
                vol.Optional(
                    CONF_ADB_PORT, default=opts.get(CONF_ADB_PORT, DEFAULT_ADB_PORT)
                ): vol.All(int, vol.Range(min=1, max=65535)),
            }
        )
        return self.async_show_form(step_id="init", data_schema=schema)
