"""Constants for the HY300 Projetor integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from datetime import timedelta
from typing import Final

DOMAIN: Final = "hy300_projetor"
DEFAULT_PORT: Final = 8899
DEFAULT_NAME: Final = "Projetor"
SCAN_INTERVAL: Final = timedelta(seconds=10)

# Options: how to turn the projector on while it is off (its Wi-Fi is down then,
# so the API can't be reached): a remote.send_command on an IR blaster.
CONF_IR_REMOTE: Final = "ir_remote"
CONF_IR_DEVICE: Final = "ir_device"
CONF_IR_COMMAND: Final = "ir_command"
DEFAULT_IR_DEVICE: Final = "projetor"
DEFAULT_IR_COMMAND: Final = "power"
CONF_IR_RETRY: Final = "ir_retry"
DEFAULT_IR_RETRY: Final = True

# After an IR power-on, poll the API directly until it answers; if it doesn't within
# POWER_ON_TIMEOUT, resend the IR once (option) and, if it still doesn't come up,
# notify + fire EVENT_POWER_ON_FAILED. Observed boot-to-API time: ~43 s.
POWER_ON_TIMEOUT: Final = timedelta(seconds=75)
POWER_ON_POLL: Final = 5
EVENT_POWER_ON_FAILED: Final = "hy300_projetor_power_on_failed"

# After turn_on/turn_off, trust the optimistic state for this long (the projector
# needs ~30 s to boot and bring Wi-Fi up; turning off drops the API immediately).
OPTIMISTIC_WINDOW: Final = timedelta(seconds=170)

# Commands the Lumina Go API accepts that must never be sent from Home Assistant.
BLOCKED_COMMANDS: Final = frozenset(
    {
        "FACTORY_RESET",
        "FACTORY_TEST",
        "CLR_DATA",
        "STRESS_TEST",
        "PIC_TEST",
        "CALIBRATION",
        "BRC_PAIR",
    }
)

# ADB (optional): app launching + "which app is on screen", via an adb server.
CONF_ADB_ENABLED: Final = "adb_enabled"
CONF_ADB_SERVER: Final = "adb_server"
CONF_ADB_PORT: Final = "adb_port"
DEFAULT_ADB_SERVER: Final = "adb-server"
DEFAULT_ADB_PORT: Final = 5037
ADB_DEVICE_PORT: Final = 5555

# "Sources" offered by the media player: label -> ("app", package) launched via ADB,
# or ("cmd", Lumina Go command) sent over the HTTP API.
SOURCES: Final = {
    "SmartTube": ("app", "org.smarttube.stable"),
    "Stremio": ("app", "com.stremio.one"),
    "Crunchyroll": ("app", "com.crunchyroll.crunchyroid"),
    "Início": ("cmd", "NAV_HOME"),
    "Todos os apps": ("cmd", "OPEN_ALL_APPS"),
    "Entrada (HDMI)": ("cmd", "INPUT_SOURCE"),
    "Espelhar tela": ("cmd", "SCREENCAST"),
    "USB": ("cmd", "USB"),
}
# Without ADB, the app entries fall back to the few Lumina Go shortcuts that exist.
SOURCE_FALLBACK_CMD: Final[dict[str, str]] = {}  # YouTube removido do projetor (SmartTube no lugar)
