"""Polls the projector to know whether it is on (the API only answers while on).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from homeassistant.config_entries import ConfigEntry
from homeassistant.components import persistent_notification
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator
from homeassistant.util import dt as dt_util

from .adb import AdbClient, AdbError
from .api import ProjectorApi, ProjectorError, ProjectorOffline
from .const import (
    ADB_DEVICE_PORT,
    CONF_ADB_ENABLED,
    CONF_ADB_PORT,
    CONF_ADB_SERVER,
    DEFAULT_ADB_PORT,
    DEFAULT_ADB_SERVER,
    CONF_IR_COMMAND,
    CONF_IR_DEVICE,
    CONF_IR_REMOTE,
    CONF_IR_RETRY,
    DEFAULT_IR_COMMAND,
    DEFAULT_IR_DEVICE,
    DEFAULT_IR_RETRY,
    DOMAIN,
    EVENT_POWER_ON_FAILED,
    OPTIMISTIC_WINDOW,
    POWER_ON_POLL,
    POWER_ON_TIMEOUT,
    SCAN_INTERVAL,
)

_LOGGER = logging.getLogger(__name__)


@dataclass
class ProjectorData:
    """What the entities read."""

    online: bool
    device: dict[str, Any] = field(default_factory=dict)
    current_package: str | None = None
    adb_ok: bool = False


class ProjectorCoordinator(DataUpdateCoordinator[ProjectorData]):
    """Being unreachable is a normal "off" state, not an update failure."""

    def __init__(self, hass: HomeAssistant, entry: ConfigEntry, api: ProjectorApi) -> None:
        super().__init__(
            hass,
            _LOGGER,
            config_entry=entry,
            name=DOMAIN,
            update_interval=SCAN_INTERVAL,
        )
        self.api = api
        self.device_info_cache: dict[str, Any] = {}
        self._optimistic: bool | None = None
        self._optimistic_until: datetime | None = None
        self._power_on_task: asyncio.Task | None = None
        opts = entry.options
        self.adb: AdbClient | None = None
        if opts.get(CONF_ADB_ENABLED):
            self.adb = AdbClient(
                opts.get(CONF_ADB_SERVER, DEFAULT_ADB_SERVER),
                opts.get(CONF_ADB_PORT, DEFAULT_ADB_PORT),
                f"{entry.data['host']}:{ADB_DEVICE_PORT}",
            )

    def set_optimistic(self, on: bool) -> None:
        """Hold a just-commanded state while the projector boots / shuts down."""
        self._optimistic = on
        self._optimistic_until = dt_util.utcnow() + OPTIMISTIC_WINDOW
        self.async_set_updated_data(
            ProjectorData(online=on, device=self.device_info_cache)
        )

    @property
    def ir_configured(self) -> bool:
        return bool(self.config_entry.options.get(CONF_IR_REMOTE))

    async def _async_send_ir_power(self) -> None:
        opts = self.config_entry.options
        remote = opts.get(CONF_IR_REMOTE)
        if not remote:
            raise HomeAssistantError("Configure o emissor de IR nas opções da integração")
        await self.hass.services.async_call(
            "remote",
            "send_command",
            {
                "entity_id": remote,
                "device": opts.get(CONF_IR_DEVICE, DEFAULT_IR_DEVICE),
                "command": opts.get(CONF_IR_COMMAND, DEFAULT_IR_COMMAND),
            },
            blocking=True,
        )

    async def async_power_on(self) -> None:
        """Turn on via the IR blaster (the API is unreachable while the projector is off)."""
        if self.data and self.data.online and self._optimistic is None:
            return
        # Already turning on: a second IR "power" would toggle it back off mid-boot.
        if self._power_on_task and not self._power_on_task.done():
            _LOGGER.debug("Power-on already in progress; ignoring repeated turn_on")
            return
        await self._async_send_ir_power()
        self.set_optimistic(True)
        self._power_on_task = self.hass.async_create_background_task(
            self._async_verify_power_on(), f"{DOMAIN}_verify_power_on"
        )

    async def _async_wait_api(self) -> bool:
        """Poll the API directly (the coordinator state is optimistic meanwhile)."""
        deadline = dt_util.utcnow() + POWER_ON_TIMEOUT
        while dt_util.utcnow() < deadline:
            try:
                self.device_info_cache = await self.api.async_get_device()
                return True
            except ProjectorError:
                await asyncio.sleep(POWER_ON_POLL)
        return False

    async def _async_verify_power_on(self) -> None:
        """Retry the IR once if the projector didn't come up; then give up and notify."""
        attempts = 1
        if not await self._async_wait_api():
            if self.config_entry.options.get(CONF_IR_RETRY, DEFAULT_IR_RETRY):
                _LOGGER.warning("Projector did not answer after IR power-on; resending IR")
                attempts = 2
                try:
                    await self._async_send_ir_power()
                except HomeAssistantError as err:
                    _LOGGER.warning("IR resend failed: %s", err)
                if await self._async_wait_api():
                    self._clear_optimistic()
                    await self.async_request_refresh()
                    return
            _LOGGER.warning("Projector did not turn on after %s IR attempt(s)", attempts)
            self._clear_optimistic()
            self.async_set_updated_data(ProjectorData(online=False, device=self.device_info_cache))
            persistent_notification.async_create(
                self.hass,
                f"O projetor não ligou depois de {attempts} tentativa(s) por infravermelho. "
                "Confira se o emissor (ZC-XZ) está apontado para o projetor e sem obstáculos, "
                "e tente de novo.",
                title="Projetor não ligou",
                notification_id=f"{DOMAIN}_power_on_failed",
            )
            self.hass.bus.async_fire(
                EVENT_POWER_ON_FAILED,
                {"entry_id": self.config_entry.entry_id, "attempts": attempts},
            )
            return
        persistent_notification.async_dismiss(self.hass, f"{DOMAIN}_power_on_failed")
        self._clear_optimistic()
        await self.async_request_refresh()

    def _clear_optimistic(self) -> None:
        self._optimistic = None
        self._optimistic_until = None

    def _cancel_power_on_check(self) -> None:
        if self._power_on_task and not self._power_on_task.done():
            self._power_on_task.cancel()
        self._power_on_task = None

    async def async_power_off(self) -> None:
        """Turn off over the API (same POWER key as the physical remote)."""
        self._cancel_power_on_check()
        await self.api.async_send_command("POWER")
        self.set_optimistic(False)

    async def async_shutdown(self) -> None:
        self._cancel_power_on_check()
        await super().async_shutdown()

    async def _async_update_data(self) -> ProjectorData:
        try:
            device = await self.api.async_get_device()
        except ProjectorOffline:
            online, device = False, {}
        except ProjectorError as err:
            _LOGGER.debug("Projector API error: %s", err)
            online, device = False, {}
        else:
            online = True
            self.device_info_cache = device

        if self._optimistic is not None and self._optimistic_until is not None:
            if dt_util.utcnow() < self._optimistic_until and online != self._optimistic:
                online = self._optimistic
            else:
                self._optimistic = None
                self._optimistic_until = None

        package = None
        adb_ok = False
        if online and self.adb and device:
            try:
                package = await self.adb.async_current_package()
                adb_ok = True
            except AdbError as err:
                _LOGGER.debug("ADB current app failed: %s", err)

        return ProjectorData(
            online=online,
            device=device or self.device_info_cache,
            current_package=package,
            adb_ok=adb_ok,
        )
