"""Base entity for HY300 Projetor.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from homeassistant.helpers.device_registry import DeviceInfo
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from .const import DOMAIN
from .coordinator import ProjectorCoordinator


class ProjectorEntity(CoordinatorEntity[ProjectorCoordinator]):
    """Shares one device card; entities stay available while the projector is off."""

    _attr_has_entity_name = True

    def __init__(self, coordinator: ProjectorCoordinator, key: str) -> None:
        super().__init__(coordinator)
        entry = coordinator.config_entry
        self._attr_unique_id = f"{entry.entry_id}_{key}"
        info = coordinator.device_info_cache
        self._attr_device_info = DeviceInfo(
            identifiers={(DOMAIN, entry.entry_id)},
            name=entry.title,
            manufacturer="HY300 / Lumina Go",
            model=info.get("model_label") or info.get("model"),
            sw_version=info.get("version"),
            configuration_url=f"http://{entry.data['host']}:{entry.data.get('port', 8899)}/",
        )
