"""Media player for HY300 Projetor.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

import logging

from homeassistant.components.media_player import (
    MediaPlayerDeviceClass,
    MediaPlayerEntity,
    MediaPlayerEntityFeature,
    MediaPlayerState,
)
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback

from . import ProjectorConfigEntry
from .adb import AdbError
from .api import ProjectorError
from .const import SOURCE_FALLBACK_CMD, SOURCES
from .entity import ProjectorEntity

_LOGGER = logging.getLogger(__name__)

BASE_FEATURES = (
    MediaPlayerEntityFeature.TURN_OFF
    | MediaPlayerEntityFeature.VOLUME_STEP
    | MediaPlayerEntityFeature.VOLUME_MUTE
    | MediaPlayerEntityFeature.PLAY
    | MediaPlayerEntityFeature.PAUSE
    | MediaPlayerEntityFeature.STOP
    | MediaPlayerEntityFeature.NEXT_TRACK
    | MediaPlayerEntityFeature.PREVIOUS_TRACK
    | MediaPlayerEntityFeature.SELECT_SOURCE
)


async def async_setup_entry(
    hass: HomeAssistant,
    entry: ProjectorConfigEntry,
    async_add_entities: AddConfigEntryEntitiesCallback,
) -> None:
    async_add_entities([ProjectorMediaPlayer(entry.runtime_data)])


class ProjectorMediaPlayer(ProjectorEntity, MediaPlayerEntity):
    """On/off from API reachability; power-on via an IR blaster (API is down while off)."""

    _attr_name = None
    _attr_device_class = MediaPlayerDeviceClass.TV

    def __init__(self, coordinator) -> None:
        super().__init__(coordinator, "media_player")
        self._source: str | None = None

    @property
    def supported_features(self) -> MediaPlayerEntityFeature:
        feats = BASE_FEATURES
        if self.coordinator.ir_configured:
            feats |= MediaPlayerEntityFeature.TURN_ON
        return feats

    @property
    def state(self) -> MediaPlayerState:
        return MediaPlayerState.ON if self.coordinator.data.online else MediaPlayerState.OFF

    @property
    def source_list(self) -> list[str]:
        if self.coordinator.adb:
            return list(SOURCES)
        return [k for k, (kind, _) in SOURCES.items() if kind == "cmd" or k in SOURCE_FALLBACK_CMD]

    @property
    def source(self) -> str | None:
        data = self.coordinator.data
        if not data.online:
            return None
        if data.current_package:
            for label, (kind, value) in SOURCES.items():
                if kind == "app" and value == data.current_package:
                    return label
        return self._source

    @property
    def app_id(self) -> str | None:
        return self.coordinator.data.current_package if self.coordinator.data.online else None

    async def _send(self, command: str) -> None:
        if not self.coordinator.data.online:
            raise HomeAssistantError("O projetor está desligado")
        try:
            await self.coordinator.api.async_send_command(command)
        except ProjectorError as err:
            raise HomeAssistantError(f"Falha ao enviar {command}: {err}") from err

    async def async_turn_on(self) -> None:
        await self.coordinator.async_power_on()

    async def async_turn_off(self) -> None:
        if not self.coordinator.data.online:
            return
        try:
            await self.coordinator.async_power_off()
        except ProjectorError as err:
            raise HomeAssistantError(f"Falha ao desligar: {err}") from err
        self._source = None

    async def async_volume_up(self) -> None:
        await self._send("VOL_UP")

    async def async_volume_down(self) -> None:
        await self._send("VOL_DOWN")

    async def async_mute_volume(self, mute: bool) -> None:
        # The API only has a toggle; there is no way to read the current mute state.
        await self._send("VOL_MUTE")

    async def async_media_play(self) -> None:
        await self._send("MEDIA_PLAY")

    async def async_media_pause(self) -> None:
        await self._send("MEDIA_PAUSE")

    async def async_media_stop(self) -> None:
        await self._send("MEDIA_STOP")

    async def async_media_next_track(self) -> None:
        await self._send("MEDIA_NEXT")

    async def async_media_previous_track(self) -> None:
        await self._send("MEDIA_PREV")

    async def async_select_source(self, source: str) -> None:
        if source not in SOURCES:
            raise HomeAssistantError(f"Fonte desconhecida: {source}")
        kind, value = SOURCES[source]
        if kind == "app":
            if self.coordinator.adb:
                if not self.coordinator.data.online:
                    raise HomeAssistantError("O projetor está desligado")
                try:
                    await self.coordinator.adb.async_launch(value)
                except AdbError as err:
                    if source in SOURCE_FALLBACK_CMD:
                        # ADB not ready yet (e.g. right after boot): use the vendor shortcut
                        await self._send(SOURCE_FALLBACK_CMD[source])
                    else:
                        raise HomeAssistantError(
                            f"Falha ao abrir {source}: o ADB ainda não está pronto ({err})"
                        ) from err
            elif source in SOURCE_FALLBACK_CMD:
                await self._send(SOURCE_FALLBACK_CMD[source])
            else:
                raise HomeAssistantError(f"{source} precisa do ADB ativado nas opções")
        else:
            await self._send(value)
        self._source = source
        self.async_write_ha_state()
        await self.coordinator.async_request_refresh()
