"""Remote entity: send any (non-destructive) Lumina Go command from automations.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home

Example:
  action: remote.send_command
  target: {entity_id: remote.projetor}
  data: {command: [NAV_DOWN, NAV_OK], delay_secs: 0.4}
"""

from __future__ import annotations

import asyncio
from collections.abc import Iterable
from typing import Any

from homeassistant.components.remote import (
    ATTR_DELAY_SECS,
    ATTR_HOLD_SECS,
    ATTR_NUM_REPEATS,
    RemoteEntity,
)
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback

from . import ProjectorConfigEntry
from .api import ProjectorError
from .entity import ProjectorEntity


async def async_setup_entry(
    hass: HomeAssistant,
    entry: ProjectorConfigEntry,
    async_add_entities: AddConfigEntryEntitiesCallback,
) -> None:
    async_add_entities([ProjectorRemote(entry.runtime_data)])


class ProjectorRemote(ProjectorEntity, RemoteEntity):
    """is_on mirrors the media player; send_command posts to /api/v1/command."""

    _attr_name = "Controle"

    def __init__(self, coordinator) -> None:
        super().__init__(coordinator, "remote")

    @property
    def is_on(self) -> bool:
        return self.coordinator.data.online

    @property
    def extra_state_attributes(self) -> dict[str, Any]:
        cmds = self.coordinator.data.device.get("commands") or []
        return {"available_commands": [c for c in cmds if isinstance(c, str)]}

    async def async_turn_on(self, **kwargs: Any) -> None:
        await self.coordinator.async_power_on()

    async def async_turn_off(self, **kwargs: Any) -> None:
        if not self.coordinator.data.online:
            return
        try:
            await self.coordinator.async_power_off()
        except ProjectorError as err:
            raise HomeAssistantError(str(err)) from err

    async def async_send_command(self, command: Iterable[str], **kwargs: Any) -> None:
        delay = kwargs.get(ATTR_DELAY_SECS, 0.4)
        repeats = kwargs.get(ATTR_NUM_REPEATS, 1)
        long_press = (kwargs.get(ATTR_HOLD_SECS) or 0) > 0
        for _ in range(repeats):
            for cmd in command:
                try:
                    await self.coordinator.api.async_send_command(cmd.strip().upper(), long_press)
                except ProjectorError as err:
                    raise HomeAssistantError(f"{cmd}: {err}") from err
                await asyncio.sleep(delay)
