"""Diagnostic sensors for HY300 Projetor.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""

from __future__ import annotations

from homeassistant.components.sensor import SensorEntity
from homeassistant.const import EntityCategory
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback

from . import ProjectorConfigEntry
from .entity import ProjectorEntity


async def async_setup_entry(
    hass: HomeAssistant,
    entry: ProjectorConfigEntry,
    async_add_entities: AddConfigEntryEntitiesCallback,
) -> None:
    async_add_entities([ProjectorFirmwareSensor(entry.runtime_data)])


class ProjectorFirmwareSensor(ProjectorEntity, SensorEntity):
    """Lumina Go firmware version (last value seen while the projector was on)."""

    _attr_name = "Firmware"
    _attr_icon = "mdi:chip"
    _attr_entity_category = EntityCategory.DIAGNOSTIC

    def __init__(self, coordinator) -> None:
        super().__init__(coordinator, "firmware")

    @property
    def native_value(self) -> str | None:
        return self.coordinator.device_info_cache.get("version")

    @property
    def extra_state_attributes(self) -> dict[str, str | None]:
        info = self.coordinator.device_info_cache
        return {"model": info.get("model"), "model_label": info.get("model_label"), "platform": info.get("name")}
