// Generated by aurora@aurora-smart-home (ha-integration-dev skill)
// https://github.com/tonylofgren/aurora-smart-home
package br.casa.adbboot;

import android.content.ContentResolver;
import android.content.Context;
import android.provider.Settings;
import android.util.Log;

final class AdbSettings {
    static final String TAG = "AdbBoot";

    private AdbSettings() {}

    /** Turn "ADB debugging" and "Wireless debugging" on. Needs WRITE_SECURE_SETTINGS. */
    static void enable(Context context, String reason) {
        ContentResolver resolver = context.getContentResolver();
        try {
            Settings.Global.putInt(resolver, "adb_enabled", 1);
            Settings.Global.putInt(resolver, "adb_wifi_enabled", 1);
            Log.i(TAG, "adb_wifi_enabled=1 (" + reason + ")");
        } catch (SecurityException e) {
            Log.e(TAG, "WRITE_SECURE_SETTINGS not granted", e);
        }
    }
}
