// Generated by aurora@aurora-smart-home (ha-integration-dev skill)
// https://github.com/tonylofgren/aurora-smart-home
package br.casa.adbboot;

import android.app.job.JobInfo;
import android.app.job.JobScheduler;
import android.content.BroadcastReceiver;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;

/** On boot: enable now, and again once a network is up (Wi-Fi may not be ready yet). */
public class BootReceiver extends BroadcastReceiver {
    static final int JOB_ID = 1;

    @Override
    public void onReceive(Context context, Intent intent) {
        AdbSettings.enable(context, String.valueOf(intent.getAction()));
        if (Intent.ACTION_BOOT_COMPLETED.equals(intent.getAction())) {
            HomeAfterBoot.run(context, goAsync());
        }
        JobScheduler scheduler = context.getSystemService(JobScheduler.class);
        if (scheduler != null) {
            scheduler.schedule(new JobInfo.Builder(
                    JOB_ID, new ComponentName(context, EnableAdbJob.class))
                    .setRequiredNetworkType(JobInfo.NETWORK_TYPE_ANY)
                    .setOverrideDeadline(120_000)
                    .build());
        }
    }
}
