// Generated by aurora@aurora-smart-home (ha-integration-dev skill)
// https://github.com/tonylofgren/aurora-smart-home
package br.casa.adbboot;

import android.app.job.JobParameters;
import android.app.job.JobService;

/** Runs once the network is connected (Wireless debugging needs Wi-Fi up). */
public class EnableAdbJob extends JobService {
    @Override
    public boolean onStartJob(JobParameters params) {
        AdbSettings.enable(this, "network up");
        return false;
    }

    @Override
    public boolean onStopJob(JobParameters params) {
        return false;
    }
}
