// Generated by aurora@aurora-smart-home (ha-integration-dev skill)
// https://github.com/tonylofgren/aurora-smart-home
package br.casa.adbboot;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.util.Log;

/**
 * The vendor launcher (com.htc.magcubicos) is direct-boot aware, so the system starts it
 * at boot before the user-chosen launcher (Projectivity) can run. When BOOT_COMPLETED
 * arrives (vendor launcher already up) fire a HOME intent -- it resolves to the default
 * launcher -- and once more 5 s later, all inside goAsync() so the process isn't frozen
 * before it runs (Android 14 freezes cached apps right after onReceive returns).
 */
final class HomeAfterBoot {
    private HomeAfterBoot() {}

    static void run(Context context, BroadcastReceiver.PendingResult pending) {
        final Context app = context.getApplicationContext();
        new Thread(() -> {
            try {
                goHome(app, "boot");
                Thread.sleep(5000);
                goHome(app, "boot+5s");
            } catch (InterruptedException ignored) {
                Thread.currentThread().interrupt();
            } finally {
                pending.finish();
            }
        }, "home-after-boot").start();
    }

    private static void goHome(Context app, String when) {
        try {
            Intent home = new Intent(Intent.ACTION_MAIN);
            home.addCategory(Intent.CATEGORY_HOME);
            home.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            app.startActivity(home);
            Log.i(AdbSettings.TAG, "HOME intent sent (" + when + ")");
        } catch (RuntimeException e) {
            Log.e(AdbSettings.TAG, "could not start HOME (" + when + ")", e);
        }
    }
}
