#!/bin/sh
# Generated by aurora@aurora-smart-home (ha-integration-dev skill)
# https://github.com/tonylofgren/aurora-smart-home
# Builds adbboot.apk inside eclipse-temurin:17-jdk (run via build-in-container.sh).
set -e
SDK=/sdk; BT=$SDK/build-tools/34.0.0; JAR=$SDK/platforms/android-34/android.jar
if [ ! -f "$JAR" ]; then
  apt-get update -qq && apt-get install -y -qq unzip zip curl >/dev/null
  curl -sL -o /tmp/ct.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
  mkdir -p $SDK/cmdline-tools && unzip -q /tmp/ct.zip -d $SDK/cmdline-tools && mv $SDK/cmdline-tools/cmdline-tools $SDK/cmdline-tools/latest
  yes | $SDK/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK --licenses >/dev/null
  $SDK/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK "build-tools;34.0.0" "platforms;android-34" >/dev/null
fi
command -v zip >/dev/null || (apt-get update -qq && apt-get install -y -qq zip >/dev/null)
cd /work && rm -rf build && mkdir -p build/classes build/dex
$BT/aapt2 link -o build/base.apk --manifest AndroidManifest.xml -I $JAR \
  --min-sdk-version 30 --target-sdk-version 34 --version-code 3 --version-name 1.2
javac -source 11 -target 11 -classpath $JAR -d build/classes $(find src -name '*.java') 2>&1 | grep -v "bootstrap classpath" || true
$BT/d8 --lib $JAR --release --min-api 30 --output build/dex $(find build/classes -name '*.class')
cp build/base.apk build/unsigned.apk && (cd build/dex && zip -q -j ../unsigned.apk classes.dex)
$BT/zipalign -f 4 build/unsigned.apk build/aligned.apk
# Signing key: KEYSTORE / KS_PASS env vars, or a local throwaway key generated on first build.
KEYSTORE=${KEYSTORE:-adbboot.keystore}; KS_PASS=${KS_PASS:-adbboot}
[ -f "$KEYSTORE" ] || keytool -genkeypair -keystore "$KEYSTORE" -storepass "$KS_PASS" -keypass "$KS_PASS" \
  -alias adbboot -keyalg RSA -keysize 2048 -validity 36500 -dname "CN=ADB Boot" >/dev/null 2>&1
$BT/apksigner sign --ks "$KEYSTORE" --ks-pass "pass:$KS_PASS" --key-pass "pass:$KS_PASS" --out adbboot.apk build/aligned.apk
$BT/apksigner verify adbboot.apk && ls -l adbboot.apk
